### ISSUE TITLE
Invoking download-as-zip as a non-admin fails

### ISSUE THREAD

**Issue by jpotts** [bhagyas/alfresco-folder-quota#5]
With this add-on installed, non-admin users cannot use Download As Zip because the behavior throws an access denied, see attached stack trace.
[download-as-zip-stack-trace.txt](https://github.com/bhagyas/alfresco-folder-quota/files/794175/download-as-zip-stack-trace.txt)

**Comment by bhagyas** [comment]
FIXED with Commit d931475
